import type { Metadata } from "next";
import { nunitoSans } from "./ui/fonts";
import "./ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-light-primary dark:bg-dark-primary ${nunitoSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
